POST http://localhost:3001/api/persons
Content-Type: application/json

# {
#     "name":"",
#     "number":""
# }

# {
#     "name":"",
#     "number":"112"
# }

# {
#     "name":"Ada Lovelace",
#     "number":""
# }

{
    "name":"Ar",
    "number":"112"
}

# {
#     "name":"Moi!",
#     "number":"112"
# }